using Agora.MODEL.Entities;
using Agora.MODEL.Enums;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Agora.DAL.Initializer
{
    public static class DataInitializer
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
        
            string pwd = BCrypt.Net.BCrypt.HashPassword("123");
            modelBuilder.Entity<User>().HasKey(k => k.ID);
            modelBuilder.Entity<User>().HasData(
               new User() { ID = 1, UserName = "admin", Password = pwd, Role = MODEL.Enums.Role.Admin  },
               new User() { ID = 2, UserName = "esra", Password = pwd, Role = MODEL.Enums.Role.Admin },
               new User() { ID = 3, UserName = "Btlkc", Password = pwd, Role = MODEL.Enums.Role.Uye },
               new User() { ID = 4, UserName = "mstfyrlmz", Password = pwd, Role = MODEL.Enums.Role.Uye }
             );
            modelBuilder.Entity<UserDetail>().HasKey(k => k.ID);
            modelBuilder.Entity<UserDetail>().HasData(
                new UserDetail() { ID = 1, NameSurname = "Admin", Phone = "00000000000", Email = "admin@gmail.com", Country = "Çorum" ,Towner= "Bayat", Gender = Gender.Female, UserID=1 },
                new UserDetail() { ID = 2, NameSurname = "Esra Yorulmaz salman" ,Email="esra@gmail.com", Phone="05432563636", Country = "Adana",Towner = "Ceyhan" ,Gender = Gender.Female, UserID=2},
                new UserDetail() { ID = 3, NameSurname = "Betül Koca", Phone = "02545896363", Email = "betul@gmail.com" , Country = "İstanbul", Towner = "Fatih", Gender = Gender.Female, UserID = 3 },
                new UserDetail() { ID = 4, NameSurname = "Mustafa Yorulmaz", Phone = "05477898989", Email = "betul@gmail.com", Country = "İstanbul", Towner = "Fatih", Gender = Gender.Male, UserID = 4 }
            );
            modelBuilder.Entity<Category>().HasKey(k => k.ID);
            modelBuilder.Entity<Category>().HasData(
               new Category() { ID = 1, CategoryName = "Elektronik" },
               new Category() { ID = 2, CategoryName = "Bilgisayar" , CategoryID=1},
               new Category() { ID = 3, CategoryName = "Telefon", CategoryID = 1 },
               new Category() { ID = 4, CategoryName = "Küçük Ev Aletleri", CategoryID = 1 },
               new Category() { ID = 5, CategoryName = "Bebek-Çocuk" },
               new Category() { ID = 6, CategoryName = "Bebek Mobilyaları" , CategoryID = 5 },
               new Category() { ID = 7, CategoryName = "Bebek Kıyafetleri", CategoryID = 5 },
               new Category() { ID = 8, CategoryName = "Bebek Oyuncakları", CategoryID = 5 },
               new Category() { ID = 9, CategoryName = "Kitap" },
               new Category() { ID = 10, CategoryName = "Ev Textil" },
               new Category() { ID = 11, CategoryName = "Halı", CategoryID = 10 },
               new Category() { ID = 12, CategoryName = "Perde, Nevresim", CategoryID = 10 },
               new Category() { ID = 13, CategoryName = "Ayakkabı - Çanta" },
               new Category() { ID = 14, CategoryName = "Ev Mobilyası" },
               new Category() { ID = 15, CategoryName = "Masa", CategoryID = 14 },
               new Category() { ID = 16, CategoryName = "Sandalye", CategoryID = 14 }
           );

            // il bilgisi
            modelBuilder.Entity<City>().HasKey(k => k.ID);
            modelBuilder.Entity<City>().HasData(
                new City() { ID = 1, CityName = "Adana" },
                new City() { ID = 2, CityName = "Adıyaman" },
                new City() { ID = 3, CityName = "Afyonkarahisar" },
                new City() { ID = 4, CityName = "Ağrı" },
                new City() { ID = 5, CityName = "Amasya" },
                new City() { ID = 6, CityName = "Ankara" },
                new City() { ID = 7, CityName = "Antalya" },
                new City() { ID = 8, CityName = "Artvin" },
                new City() { ID = 9, CityName = "Aydın" },
                new City() { ID = 10, CityName = "Balıkesir" },
                new City() { ID = 11, CityName = "Bilecik" },
                new City() { ID = 12, CityName = "Bingöl" },
                new City() { ID = 13, CityName = "Bitlis" },
                new City() { ID = 14, CityName = "Bolu" },
                new City() { ID = 15, CityName = "Burdur" },
                new City() { ID = 16, CityName = "Bursa" },
                new City() { ID = 17, CityName = "Çanakkale" },
                new City() { ID = 18, CityName = "Çankırı" },
                new City() { ID = 19, CityName = "Çorum" },
                new City() { ID = 20, CityName = "Denizli" },
                new City() { ID = 21, CityName = "Diyarbakır" },
                new City() { ID = 22, CityName = "Edirne" },
                new City() { ID = 23, CityName = "Elazığ" },
                new City() { ID = 24, CityName = "Erzincan" },
                new City() { ID = 25, CityName = "Erzurum" },
                new City() { ID = 26, CityName = "Eskişehir" },
                new City() { ID = 27, CityName = "Gaziantep" },
                new City() { ID = 28, CityName = "Giresun" },
                new City() { ID = 29, CityName = "Gümüşhane" },
                new City() { ID = 30, CityName = "Hakkari" },
                new City() { ID = 31, CityName = "Hatay" },
                new City() { ID = 32, CityName = "Isparta" },
                new City() { ID = 33, CityName = "Mersin" },
                new City() { ID = 34, CityName = "İstanbul" },
                new City() { ID = 35, CityName = "İzmir" },
                new City() { ID = 36, CityName = "Kars" },
                new City() { ID = 37, CityName = "Kastamonu" },
                new City() { ID = 38, CityName = "Kayseri" },
                new City() { ID = 39, CityName = "Kırklareli" },
                new City() { ID = 40, CityName = "Kırşehir" },
                new City() { ID = 41, CityName = "Kocaeli" },
                new City() { ID = 42, CityName = "Konya" },
                new City() { ID = 43, CityName = "Kütahya" },
                new City() { ID = 44, CityName = "Malatya" },
                new City() { ID = 45, CityName = "Manisa" },
                new City() { ID = 46, CityName = "Kahramanmaraş" },
                new City() { ID = 47, CityName = "Mardin" },
                new City() { ID = 48, CityName = "Muğla" },
                new City() { ID = 49, CityName = "Muş" },
                new City() { ID = 50, CityName = "Nevşehir" },
                new City() { ID = 51, CityName = "Niğde" },
                new City() { ID = 52, CityName = "Ordu" },
                new City() { ID = 53, CityName = "Rize" },
                new City() { ID = 54, CityName = "Sakarya" },
                new City() { ID = 55, CityName = "Samsun" },
                new City() { ID = 56, CityName = "Siirt" },
                new City() { ID = 57, CityName = "Sinop" },
                new City() { ID = 58, CityName = "Sivas" },
                new City() { ID = 59, CityName = "Tekirdağ" },
                new City() { ID = 60, CityName = "Tokat" },
                new City() { ID = 61, CityName = "Trabzon" },
                new City() { ID = 62, CityName = "Tunceli" },
                new City() { ID = 63, CityName = "Şanlıurfa" },
                new City() { ID = 64, CityName = "Uşak" },
                new City() { ID = 65, CityName = "Van" },
                new City() { ID = 66, CityName = "Yozgat" },
                new City() { ID = 67, CityName = "Zonguldak" },
                new City() { ID = 68, CityName = "Aksaray" },
                new City() { ID = 69, CityName = "Bayburt" },
                new City() { ID = 70, CityName = "Karaman" },
                new City() { ID = 71, CityName = "Kırıkkale" },
                new City() { ID = 72, CityName = "Batman" },
                new City() { ID = 73, CityName = "Şırnak" },
                new City() { ID = 74, CityName = "Bartın" },
                new City() { ID = 75, CityName = "Ardahan" },
                new City() { ID = 76, CityName = "Iğdır" },
                new City() { ID = 77, CityName = "Yalova" },
                new City() { ID = 78, CityName = "Karabük" },
                new City() { ID = 79, CityName = "Kilis" },
                new City() { ID = 80, CityName = "Osmaniye" },
                new City() { ID = 81, CityName = "Düzce" }
                );

            modelBuilder.Entity<Town>().HasData(
                new Town() { ID = 1, TownName = "Seyhan", CityID = 1 },
                new Town() { ID = 2, TownName = "Ceyhan", CityID = 1 },
                new Town() { ID = 3, TownName = "Feke", CityID = 1 },
                new Town() { ID = 4, TownName = "Karaisalı", CityID = 1 },
                new Town() { ID = 5, TownName = "Karataş", CityID = 1 },
                new Town() { ID = 6, TownName = "Kozan", CityID = 1 },
                new Town() { ID = 7, TownName = "Pozantı", CityID = 1 },
                new Town() { ID = 8, TownName = "Saimbeyli", CityID = 1 },
                new Town() { ID = 9, TownName = "Tufanbeyli", CityID = 1 },
                new Town() { ID = 10, TownName = "Yumurtalık", CityID = 1 },
                new Town() { ID = 11, TownName = "Yüreğir", CityID = 1 },
                new Town() { ID = 12, TownName = "Aladağ", CityID = 1 },
                new Town() { ID = 13, TownName = "İmamoğlu", CityID = 1 },
                new Town() { ID = 14, TownName = "Sarıçam", CityID = 1 },
                new Town() { ID = 15, TownName = "Çukurova", CityID = 1 },
                new Town() { ID = 16, TownName = "Adıyaman Merkez", CityID = 2 },
                new Town() { ID = 17, TownName = "Besni", CityID = 2 },
                new Town() { ID = 18, TownName = "Çelikhan", CityID = 2 },
                new Town() { ID = 19, TownName = "Gerger", CityID = 2 },
                new Town() { ID = 20, TownName = "Gölbaşı", CityID = 2 },
                new Town() { ID = 21, TownName = "Kahta", CityID = 2 },
                new Town() { ID = 22, TownName = "Samsat", CityID = 2 },
                new Town() { ID = 23, TownName = "Sincik", CityID = 2 },
                new Town() { ID = 24, TownName = "Tut", CityID = 2 },
                new Town() { ID = 25, TownName = "Afyonkarahisar", CityID = 3 },
                new Town() { ID = 26, TownName = "Bolvadin", CityID = 3 },
                new Town() { ID = 27, TownName = "Çay", CityID = 3 },
                new Town() { ID = 28, TownName = "Dazkırı", CityID = 3 },
                new Town() { ID = 29, TownName = "Dinar", CityID = 3 },
                new Town() { ID = 30, TownName = "Emirdağ", CityID = 3 },
                new Town() { ID = 31, TownName = "İhsaniye", CityID = 3 },
                new Town() { ID = 32, TownName = "Sandıklı", CityID = 3 },
                new Town() { ID = 33, TownName = "Sinanpaşa", CityID = 3 },
                new Town() { ID = 34, TownName = "Sultandağı", CityID = 3 },
                new Town() { ID = 35, TownName = "Şuhut", CityID = 3 },
                new Town() { ID = 36, TownName = "Başmakçı", CityID = 3 },
                new Town() { ID = 37, TownName = "Bayat", CityID = 3 },
                new Town() { ID = 38, TownName = "İscehisar", CityID = 3 },
                new Town() { ID = 39, TownName = "Çobanlar", CityID = 3 },
                new Town() { ID = 40, TownName = "Evciler", CityID = 3 },
                new Town() { ID = 41, TownName = "Hocalar", CityID = 3 },
                new Town() { ID = 42, TownName = "Kızılören", CityID = 3 },
                new Town() { ID = 43, TownName = "Ağrı Merkez", CityID = 4 },
                new Town() { ID = 44, TownName = "Diyadin", CityID = 4 },
                new Town() { ID = 45, TownName = "Doğubayazıt", CityID = 4 },
                new Town() { ID = 46, TownName = "Eleşkirt", CityID = 4 },
                new Town() { ID = 47, TownName = "Hamur", CityID = 4 },
                new Town() { ID = 48, TownName = "Patnos", CityID = 4 },
                new Town() { ID = 49, TownName = "Taşlıçay", CityID = 4 },
                new Town() { ID = 50, TownName = "Tutak", CityID = 4 },
                new Town() { ID = 51, TownName = "Amasya Merkez", CityID = 5 },
                new Town() { ID = 52, TownName = "Göynücek", CityID = 5 },
                new Town() { ID = 53, TownName = "Gümüşhacıköy", CityID = 5 },
                new Town() { ID = 54, TownName = "Merzifon", CityID = 5 },
                new Town() { ID = 55, TownName = "Suluova", CityID = 5 },
                new Town() { ID = 56, TownName = "Taşova", CityID = 5 },
                new Town() { ID = 57, TownName = "Hamamözü", CityID = 5 },
                new Town() { ID = 58, TownName = "Altındağ", CityID = 6 },
                new Town() { ID = 59, TownName = "Ayaş", CityID = 6 },
                new Town() { ID = 60, TownName = "Bala", CityID = 6 },
                new Town() { ID = 61, TownName = "Beypazarı", CityID = 6 },
                new Town() { ID = 62, TownName = "Çamlıdere", CityID = 6 },
                new Town() { ID = 63, TownName = "Çankaya", CityID = 6 },
                new Town() { ID = 64, TownName = "Çubuk", CityID = 6 },
                new Town() { ID = 65, TownName = "Elmadağ", CityID = 6 },
                new Town() { ID = 66, TownName = "Güdül", CityID = 6 },
                new Town() { ID = 67, TownName = "Haymana", CityID = 6 },
                new Town() { ID = 68, TownName = "Kalecik", CityID = 6 },
                new Town() { ID = 69, TownName = "Kızılcahamam", CityID = 6 },
                new Town() { ID = 70, TownName = "Nallıhan", CityID = 6 },
                new Town() { ID = 71, TownName = "Polatlı", CityID = 6 },
                new Town() { ID = 72, TownName = "Şereflikoçhisar", CityID = 6 },
                new Town() { ID = 73, TownName = "Yenimahalle", CityID = 6 },
                new Town() { ID = 74, TownName = "Gölbaşı", CityID = 6 },
                new Town() { ID = 75, TownName = "Keçiören", CityID = 6 },
                new Town() { ID = 76, TownName = "Mamak", CityID = 6 },
                new Town() { ID = 77, TownName = "Sincan", CityID = 6 },
                new Town() { ID = 78, TownName = "Kazan", CityID = 6 },
                new Town() { ID = 79, TownName = "Akyurt", CityID = 6 },
                new Town() { ID = 80, TownName = "Etimesgut", CityID = 6 },
                new Town() { ID = 81, TownName = "Evren", CityID = 6 },
                new Town() { ID = 82, TownName = "Pursaklar", CityID = 6 },
                new Town() { ID = 83, TownName = "Akseki", CityID = 7 },
                new Town() { ID = 84, TownName = "Alanya", CityID = 7 },
                new Town() { ID = 85, TownName = "Elmalı", CityID = 7 },
                new Town() { ID = 86, TownName = "Finike", CityID = 7 },
                new Town() { ID = 87, TownName = "Gazipaşa", CityID = 7 },
                new Town() { ID = 88, TownName = "Gündoğmuş", CityID = 7 },
                new Town() { ID = 89, TownName = "Kaş", CityID = 7 },
                new Town() { ID = 90, TownName = "Korkuteli", CityID = 7 },
                new Town() { ID = 91, TownName = "Kumluca", CityID = 7 },
                new Town() { ID = 92, TownName = "Manavgat", CityID = 7 },
                new Town() { ID = 93, TownName = "Serik", CityID = 7 },
                new Town() { ID = 94, TownName = "Demre", CityID = 7 },
                new Town() { ID = 95, TownName = "İbradı", CityID = 7 },
                new Town() { ID = 96, TownName = "Kemer", CityID = 7 },
                new Town() { ID = 97, TownName = "Aksu", CityID = 7 },
                new Town() { ID = 98, TownName = "Döşemealtı", CityID = 7 },
                new Town() { ID = 99, TownName = "Kepez", CityID = 7 },
                new Town() { ID = 100, TownName = "Konyaaltı", CityID = 7 },
                new Town() { ID = 101, TownName = "Muratpaşa", CityID = 7 },
                new Town() { ID = 102, TownName = "Ardanuç", CityID = 8 },
                new Town() { ID = 103, TownName = "Arhavi", CityID = 8 },
                new Town() { ID = 104, TownName = "Artvin Merkez", CityID = 8 },
                new Town() { ID = 105, TownName = "Borçka", CityID = 8 },
                new Town() { ID = 106, TownName = "Hopa", CityID = 8 },
                new Town() { ID = 107, TownName = "Şavşat", CityID = 8 },
                new Town() { ID = 108, TownName = "Yusufeli", CityID = 8 },
                new Town() { ID = 109, TownName = "Murgul", CityID = 8 },
                new Town() { ID = 110, TownName = "Bozdoğan", CityID = 9 },
                new Town() { ID = 111, TownName = "Çine", CityID = 9 },
                new Town() { ID = 112, TownName = "Germencik", CityID = 9 },
                new Town() { ID = 113, TownName = "Karacasu", CityID = 9 },
                new Town() { ID = 114, TownName = "Koçarlı", CityID = 9 },
                new Town() { ID = 115, TownName = "Kuşadası", CityID = 9 },
                new Town() { ID = 116, TownName = "Kuyucak", CityID = 9 },
                new Town() { ID = 117, TownName = "Nazilli", CityID = 9 },
                new Town() { ID = 118, TownName = "Söke", CityID = 9 },
                new Town() { ID = 119, TownName = "Sultanhisar", CityID = 9 },
                new Town() { ID = 120, TownName = "Yenipazar", CityID = 9 },
                new Town() { ID = 121, TownName = "Buharkent", CityID = 9 },
                new Town() { ID = 122, TownName = "İncirliova", CityID = 9 },
                new Town() { ID = 123, TownName = "Karpuzlu", CityID = 9 },
                new Town() { ID = 124, TownName = "Köşk", CityID = 9 },
                new Town() { ID = 125, TownName = "Didim", CityID = 9 },
                new Town() { ID = 126, TownName = "Efeler", CityID = 9 },
                new Town() { ID = 127, TownName = "Ayvalık", CityID = 10 },
                new Town() { ID = 128, TownName = "Balya", CityID = 10 },
                new Town() { ID = 129, TownName = "Bandırma", CityID = 10 },
                new Town() { ID = 130, TownName = "Bigadiç", CityID = 10 },
                new Town() { ID = 131, TownName = "Burhaniye", CityID = 10 },
                new Town() { ID = 132, TownName = "Dursunbey", CityID = 10 },
                new Town() { ID = 133, TownName = "Edremit", CityID = 10 },
                new Town() { ID = 134, TownName = "Erdek", CityID = 10 },
                new Town() { ID = 135, TownName = "Gönen", CityID = 10 },
                new Town() { ID = 136, TownName = "Havran", CityID = 10 },
                new Town() { ID = 137, TownName = "İvrindi", CityID = 10 },
                new Town() { ID = 138, TownName = "Kepsut", CityID = 10 },
                new Town() { ID = 139, TownName = "Manyas", CityID = 10 },
                new Town() { ID = 140, TownName = "Savaştepe", CityID = 10 },
                new Town() { ID = 141, TownName = "Sındırgı", CityID = 10 },
                new Town() { ID = 142, TownName = "Susurluk", CityID = 10 },
                new Town() { ID = 143, TownName = "Marmara", CityID = 10 },
                new Town() { ID = 144, TownName = "Gömeç", CityID = 10 },
                new Town() { ID = 145, TownName = "Altıeylül", CityID = 10 },
                new Town() { ID = 146, TownName = "Karesi", CityID = 10 },
                new Town() { ID = 147, TownName = "Bilecik", CityID = 11 },
                new Town() { ID = 148, TownName = "Bozüyük", CityID = 11 },
                new Town() { ID = 149, TownName = "Gölpazarı", CityID = 11 },
                new Town() { ID = 150, TownName = "Osmaneli", CityID = 11 },
                new Town() { ID = 151, TownName = "Pazaryeri", CityID = 11 },
                new Town() { ID = 152, TownName = "Söğüt", CityID = 11 },
                new Town() { ID = 153, TownName = "Yenipazar", CityID = 11 },
                new Town() { ID = 154, TownName = "İnhisar", CityID = 11 },
                new Town() { ID = 155, TownName = "Bingöl", CityID = 12 },
                new Town() { ID = 156, TownName = "Genç", CityID = 12 },
                new Town() { ID = 157, TownName = "Karlıova", CityID = 12 },
                new Town() { ID = 158, TownName = "Kiğı", CityID = 12 },
                new Town() { ID = 159, TownName = "Solhan", CityID = 12 },
                new Town() { ID = 160, TownName = "Adaklı", CityID = 12 },
                new Town() { ID = 161, TownName = "Yayladere", CityID = 12 },
                new Town() { ID = 162, TownName = "Yedisu", CityID = 12 },
                new Town() { ID = 163, TownName = "Adilcevaz", CityID = 13 },
                new Town() { ID = 164, TownName = "Ahlat", CityID = 13 },
                new Town() { ID = 165, TownName = "Bitlis", CityID = 13 },
                new Town() { ID = 166, TownName = "Hizan", CityID = 13 },
                new Town() { ID = 167, TownName = "Mutki", CityID = 13 },
                new Town() { ID = 168, TownName = "Tatvan", CityID = 13 },
                new Town() { ID = 169, TownName = "Güroymak", CityID = 13 },
                new Town() { ID = 170, TownName = "Bolu", CityID = 14 },
                new Town() { ID = 171, TownName = "Gerede", CityID = 14 },
                new Town() { ID = 172, TownName = "Göynük", CityID = 14 },
                new Town() { ID = 173, TownName = "Kıbrıscık", CityID = 14 },
                new Town() { ID = 174, TownName = "Mengen", CityID = 14 },
                new Town() { ID = 175, TownName = "Mudurnu", CityID = 14 },
                new Town() { ID = 176, TownName = "Seben", CityID = 14 },
                new Town() { ID = 177, TownName = "Dörtdivan", CityID = 14 },
                new Town() { ID = 178, TownName = "Yeniçağa", CityID = 14 },
                new Town() { ID = 179, TownName = "Ağlasun", CityID = 15 },
                new Town() { ID = 180, TownName = "Bucak", CityID = 15 },
                new Town() { ID = 181, TownName = "Burdur", CityID = 15 },
                new Town() { ID = 182, TownName = "Gölhisar", CityID = 15 },
                new Town() { ID = 183, TownName = "Tefenni", CityID = 15 },
                new Town() { ID = 184, TownName = "Yeşilova", CityID = 15 },
                new Town() { ID = 185, TownName = "Karamanlı", CityID = 15 },
                new Town() { ID = 186, TownName = "Kemer", CityID = 15 },
                new Town() { ID = 187, TownName = "Altınyayla", CityID = 15 },
                new Town() { ID = 188, TownName = "Çavdır", CityID = 15 },
                new Town() { ID = 189, TownName = "Çeltikçi", CityID = 15 },
                new Town() { ID = 190, TownName = "Gemlik", CityID = 16 },
                new Town() { ID = 191, TownName = "İnegöl", CityID = 16 },
                new Town() { ID = 192, TownName = "İznik", CityID = 16 },
                new Town() { ID = 193, TownName = "Karacabey", CityID = 16 },
                new Town() { ID = 194, TownName = "Keles", CityID = 16 },
                new Town() { ID = 195, TownName = "Mudanya", CityID = 16 },
                new Town() { ID = 196, TownName = "Mustafakemalpaşa", CityID = 16 },
                new Town() { ID = 197, TownName = "Orhaneli", CityID = 16 },
                new Town() { ID = 198, TownName = "Orhangazi", CityID = 16 },
                new Town() { ID = 199, TownName = "Yenişehir", CityID = 16 },
                new Town() { ID = 200, TownName = "Büyükorhan", CityID = 16 },
                new Town() { ID = 201, TownName = "Harmancık", CityID = 16 },
                new Town() { ID = 202, TownName = "Nilüfer", CityID = 16 },
                new Town() { ID = 203, TownName = "Osmangazi", CityID = 16 },
                new Town() { ID = 204, TownName = "Yıldırım", CityID = 16 },
                new Town() { ID = 205, TownName = "Gürsu", CityID = 16 },
                new Town() { ID = 206, TownName = "Kestel", CityID = 16 },
                new Town() { ID = 207, TownName = "Ayvacık", CityID = 17 },
                new Town() { ID = 208, TownName = "Bayramiç", CityID = 17 },
                new Town() { ID = 209, TownName = "Biga", CityID = 17 },
                new Town() { ID = 210, TownName = "Bozcaada", CityID = 17 },
                new Town() { ID = 211, TownName = "Çan", CityID = 17 },
                new Town() { ID = 212, TownName = "Çanakkale", CityID = 17 },
                new Town() { ID = 213, TownName = "Eceabat", CityID = 17 },
                new Town() { ID = 214, TownName = "Ezine", CityID = 17 },
                new Town() { ID = 215, TownName = "Gelibolu", CityID = 17 },
                new Town() { ID = 216, TownName = "Gökçeada", CityID = 17 },
                new Town() { ID = 217, TownName = "Lapseki", CityID = 17 },
                new Town() { ID = 218, TownName = "Yenice", CityID = 17 },
                new Town() { ID = 219, TownName = "Çankırı", CityID = 18 },
                new Town() { ID = 220, TownName = "Çerkeş", CityID = 18 },
                new Town() { ID = 221, TownName = "Eldivan", CityID = 18 },
                new Town() { ID = 222, TownName = "Ilgaz", CityID = 18 },
                new Town() { ID = 223, TownName = "Kurşunlu", CityID = 18 },
                new Town() { ID = 224, TownName = "Orta", CityID = 18 },
                new Town() { ID = 225, TownName = "Şabanözü", CityID = 18 },
                new Town() { ID = 226, TownName = "Yapraklı", CityID = 18 },
                new Town() { ID = 227, TownName = "Atkaracalar", CityID = 18 },
                new Town() { ID = 228, TownName = "Kızılırmak", CityID = 18 },
                new Town() { ID = 229, TownName = "Bayramören", CityID = 18 },
                new Town() { ID = 230, TownName = "Korgun", CityID = 18 },
                new Town() { ID = 231, TownName = "Alaca", CityID = 19 },
                new Town() { ID = 232, TownName = "Bayat", CityID = 19 },
                new Town() { ID = 233, TownName = "Merkez", CityID = 19 },
                new Town() { ID = 234, TownName = "İskilip", CityID = 19 },
                new Town() { ID = 235, TownName = "Kargı", CityID = 19 },
                new Town() { ID = 236, TownName = "Mecitözü", CityID = 19 },
                new Town() { ID = 237, TownName = "Ortaköy", CityID = 19 },
                new Town() { ID = 238, TownName = "Osmancık", CityID = 19 },
                new Town() { ID = 239, TownName = "Sungurlu", CityID = 19 },
                new Town() { ID = 240, TownName = "Boğazkale", CityID = 19 },
                new Town() { ID = 241, TownName = "Uğurludağ", CityID = 19 },
                new Town() { ID = 242, TownName = "Dodurga", CityID = 19 },
                new Town() { ID = 243, TownName = "Laçin", CityID = 19 },
                new Town() { ID = 244, TownName = "Oğuzlar", CityID = 19 },
                new Town() { ID = 245, TownName = "Acıpayam", CityID = 20 },
                new Town() { ID = 246, TownName = "Buldan", CityID = 20 },
                new Town() { ID = 247, TownName = "Çal", CityID = 20 },
                new Town() { ID = 248, TownName = "Çameli", CityID = 20 },
                new Town() { ID = 249, TownName = "Çardak", CityID = 20 },
                new Town() { ID = 250, TownName = "Çivril", CityID = 20 },
                new Town() { ID = 251, TownName = "Güney", CityID = 20 },
                new Town() { ID = 252, TownName = "Kale", CityID = 20 },
                new Town() { ID = 253, TownName = "Sarayköy", CityID = 20 },
                new Town() { ID = 254, TownName = "Tavas", CityID = 20 },
                new Town() { ID = 255, TownName = "Babadağ", CityID = 20 },
                new Town() { ID = 256, TownName = "Bekilli", CityID = 20 },
                new Town() { ID = 257, TownName = "Honaz", CityID = 20 },
                new Town() { ID = 258, TownName = "Serinhisar", CityID = 20 },
                new Town() { ID = 259, TownName = "Pamukkale", CityID = 20 },
                new Town() { ID = 260, TownName = "Baklan", CityID = 20 },
                new Town() { ID = 261, TownName = "Beyağaç", CityID = 20 },
                new Town() { ID = 262, TownName = "Bozkurt", CityID = 20 },
                new Town() { ID = 263, TownName = "Merkezefendi", CityID = 20 },
                new Town() { ID = 264, TownName = "Bismil", CityID = 21 },
                new Town() { ID = 265, TownName = "Çermik", CityID = 21 },
                new Town() { ID = 266, TownName = "Çınar", CityID = 21 },
                new Town() { ID = 267, TownName = "Çüngüş", CityID = 21 },
                new Town() { ID = 268, TownName = "Dicle", CityID = 21 },
                new Town() { ID = 269, TownName = "Ergani", CityID = 21 },
                new Town() { ID = 270, TownName = "Hani", CityID = 21 },
                new Town() { ID = 271, TownName = "Hazro", CityID = 21 },
                new Town() { ID = 272, TownName = "Kulp", CityID = 21 },
                new Town() { ID = 273, TownName = "Lice", CityID = 21 },
                new Town() { ID = 274, TownName = "Silvan", CityID = 21 },
                new Town() { ID = 275, TownName = "Eğil", CityID = 21 },
                new Town() { ID = 276, TownName = "Kocaköy", CityID = 21 },
                new Town() { ID = 277, TownName = "Bağlar", CityID = 21 },
                new Town() { ID = 278, TownName = "Kayapınar", CityID = 21 },
                new Town() { ID = 279, TownName = "Sur", CityID = 21 },
                new Town() { ID = 280, TownName = "Yenişehir", CityID = 21 },
                new Town() { ID = 281, TownName = "Merkez", CityID = 22 },
                new Town() { ID = 282, TownName = "Enez", CityID = 22 },
                new Town() { ID = 283, TownName = "Havsa", CityID = 22 },
                new Town() { ID = 284, TownName = "İpsala", CityID = 22 },
                new Town() { ID = 285, TownName = "Keşan", CityID = 22 },
                new Town() { ID = 286, TownName = "Lalapaşa", CityID = 22 },
                new Town() { ID = 287, TownName = "Meriç", CityID = 22 },
                new Town() { ID = 288, TownName = "Uzunköprü", CityID = 22 },
                new Town() { ID = 289, TownName = "Süloğlu", CityID = 22 },
                new Town() { ID = 290, TownName = "Ağın", CityID = 23 },
                new Town() { ID = 291, TownName = "Baskil", CityID = 23 },
                new Town() { ID = 292, TownName = "Merkez", CityID = 23 },
                new Town() { ID = 293, TownName = "Karakoçan", CityID = 23 },
                new Town() { ID = 294, TownName = "Keban", CityID = 23 },
                new Town() { ID = 295, TownName = "Maden", CityID = 23 },
                new Town() { ID = 296, TownName = "Palu", CityID = 23 },
                new Town() { ID = 297, TownName = "Sivrice", CityID = 23 },
                new Town() { ID = 298, TownName = "Arıcak", CityID = 23 },
                new Town() { ID = 299, TownName = "Kovancılar", CityID = 23 },
                new Town() { ID = 300, TownName = "Alacakaya", CityID = 23 },
                new Town() { ID = 301, TownName = "Çayırlı", CityID = 24 },
                new Town() { ID = 302, TownName = "Merkez", CityID = 24 },
                new Town() { ID = 303, TownName = "İliç", CityID = 24 },
                new Town() { ID = 304, TownName = "Kemah", CityID = 24 },
                new Town() { ID = 305, TownName = "Kemaliye", CityID = 24 },
                new Town() { ID = 306, TownName = "Refahiye", CityID = 24 },
                new Town() { ID = 307, TownName = "Tercan", CityID = 24 },
                new Town() { ID = 308, TownName = "Üzümlü", CityID = 24 },
                new Town() { ID = 309, TownName = "Otlukbeli", CityID = 24 },
                new Town() { ID = 310, TownName = "Aşkale", CityID = 25 },
                new Town() { ID = 311, TownName = "Çat", CityID = 25 },
                new Town() { ID = 312, TownName = "Hınıs", CityID = 25 },
                new Town() { ID = 313, TownName = "Horasan", CityID = 25 },
                new Town() { ID = 314, TownName = "İspir", CityID = 25 },
                new Town() { ID = 315, TownName = "Karayazı", CityID = 25 },
                new Town() { ID = 316, TownName = "Narman", CityID = 25 },
                new Town() { ID = 317, TownName = "Oltu", CityID = 25 },
                new Town() { ID = 318, TownName = "Olur", CityID = 25 },
                new Town() { ID = 319, TownName = "Pasinler", CityID = 25 },
                new Town() { ID = 320, TownName = "Şenkaya", CityID = 25 },
                new Town() { ID = 321, TownName = "Tekman", CityID = 25 },
                new Town() { ID = 322, TownName = "Tortum", CityID = 25 },
                new Town() { ID = 323, TownName = "Karaçoban", CityID = 25 },
                new Town() { ID = 324, TownName = "Uzundere", CityID = 25 },
                new Town() { ID = 325, TownName = "Pazaryolu", CityID = 25 },
                new Town() { ID = 326, TownName = "Aziziye", CityID = 25 },
                new Town() { ID = 327, TownName = "Köprüköy", CityID = 25 },
                new Town() { ID = 328, TownName = "Palandöken", CityID = 25 },
                new Town() { ID = 329, TownName = "Yakutiye", CityID = 25 },
                new Town() { ID = 330, TownName = "Çifteler", CityID = 26 },
                new Town() { ID = 331, TownName = "Mahmudiye", CityID = 26 },
                new Town() { ID = 332, TownName = "Mihalıççık", CityID = 26 },
                new Town() { ID = 333, TownName = "Sarıcakaya", CityID = 26 },
                new Town() { ID = 334, TownName = "Seyitgazi", CityID = 26 },
                new Town() { ID = 335, TownName = "Sivrihisar", CityID = 26 },
                new Town() { ID = 336, TownName = "Alpu", CityID = 26 },
                new Town() { ID = 337, TownName = "Beylikova", CityID = 26 },
                new Town() { ID = 338, TownName = "İnönü", CityID = 26 },
                new Town() { ID = 339, TownName = "Günyüzü", CityID = 26 },
                new Town() { ID = 340, TownName = "Han", CityID = 26 },
                new Town() { ID = 341, TownName = "Mihalgazi", CityID = 26 },
                new Town() { ID = 342, TownName = "Odunpazarı", CityID = 26 },
                new Town() { ID = 343, TownName = "Tepebaşı", CityID = 26 },
                new Town() { ID = 344, TownName = "Araban", CityID = 27 },
                new Town() { ID = 345, TownName = "İslahiye", CityID = 27 },
                new Town() { ID = 346, TownName = "Nizip", CityID = 27 },
                new Town() { ID = 347, TownName = "Oğuzeli", CityID = 27 },
                new Town() { ID = 348, TownName = "Yavuzeli", CityID = 27 },
                new Town() { ID = 349, TownName = "Şahinbey", CityID = 27 },
                new Town() { ID = 350, TownName = "Şehitkamil", CityID = 27 },
                new Town() { ID = 351, TownName = "Karkamış", CityID = 27 },
                new Town() { ID = 352, TownName = "Nurdağı", CityID = 27 },
                new Town() { ID = 353, TownName = "Alucra", CityID = 28 },
                new Town() { ID = 354, TownName = "Bulancak", CityID = 28 },
                new Town() { ID = 355, TownName = "Dereli", CityID = 28 },
                new Town() { ID = 356, TownName = "Espiye", CityID = 28 },
                new Town() { ID = 357, TownName = "Eynesil", CityID = 28 },
                new Town() { ID = 358, TownName = "Merkez", CityID = 28 },
                new Town() { ID = 359, TownName = "Görele", CityID = 28 },
                new Town() { ID = 360, TownName = "Keşap", CityID = 28 },
                new Town() { ID = 361, TownName = "Şebinkarahisar", CityID = 28 },
                new Town() { ID = 362, TownName = "Tirebolu", CityID = 28 },
                new Town() { ID = 363, TownName = "Piraziz", CityID = 28 },
                new Town() { ID = 364, TownName = "Yağlıdere", CityID = 28 },
                new Town() { ID = 365, TownName = "Çamoluk", CityID = 28 },
                new Town() { ID = 366, TownName = "Çanakçı", CityID = 28 },
                new Town() { ID = 367, TownName = "Doğankent", CityID = 28 },
                new Town() { ID = 368, TownName = "Güce", CityID = 28 },
                new Town() { ID = 369, TownName = "Merkez", CityID = 29 },
                new Town() { ID = 370, TownName = "Kelkit", CityID = 29 },
                new Town() { ID = 371, TownName = "Şiran", CityID = 29 },
                new Town() { ID = 372, TownName = "Torul", CityID = 29 },
                new Town() { ID = 373, TownName = "Köse", CityID = 29 },
                new Town() { ID = 374, TownName = "Kürtün", CityID = 29 },
                new Town() { ID = 375, TownName = "Çukurca", CityID = 30 },
                new Town() { ID = 376, TownName = "Merkez", CityID = 30 },
                new Town() { ID = 377, TownName = "Şemdinli", CityID = 30 },
                new Town() { ID = 378, TownName = "Yüksekova", CityID = 30 },
                new Town() { ID = 379, TownName = "Altınözü", CityID = 31 },
                new Town() { ID = 380, TownName = "Dörtyol", CityID = 31 },
                new Town() { ID = 381, TownName = "Hassa", CityID = 31 },
                new Town() { ID = 382, TownName = "İskenderun", CityID = 31 },
                new Town() { ID = 383, TownName = "Kırıkhan", CityID = 31 },
                new Town() { ID = 384, TownName = "Reyhanlı", CityID = 31 },
                new Town() { ID = 385, TownName = "Samandağ", CityID = 31 },
                new Town() { ID = 386, TownName = "Yayladağı", CityID = 31 },
                new Town() { ID = 387, TownName = "Erzin", CityID = 31 },
                new Town() { ID = 388, TownName = "Belen", CityID = 31 },
                new Town() { ID = 389, TownName = "Kumlu", CityID = 31 },
                new Town() { ID = 390, TownName = "Antakya", CityID = 31 },
                new Town() { ID = 391, TownName = "Arsuz", CityID = 31 },
                new Town() { ID = 392, TownName = "Defne", CityID = 31 },
                new Town() { ID = 393, TownName = "Payas", CityID = 31 },
                new Town() { ID = 394, TownName = "Atabey", CityID = 32 },
                new Town() { ID = 395, TownName = "Eğirdir", CityID = 32 },
                new Town() { ID = 396, TownName = "Gelendost", CityID = 32 },
                new Town() { ID = 397, TownName = "Merkez", CityID = 32 },
                new Town() { ID = 398, TownName = "Keçiborlu", CityID = 32 },
                new Town() { ID = 399, TownName = "Senirkent", CityID = 32 },
                new Town() { ID = 400, TownName = "Sütçüler", CityID = 32 },
                new Town() { ID = 401, TownName = "Şarkikaraağaç", CityID = 32 },
                new Town() { ID = 402, TownName = "Uluborlu", CityID = 32 },
                new Town() { ID = 403, TownName = "Yalvaç", CityID = 32 },
                new Town() { ID = 404, TownName = "Aksu", CityID = 32 },
                new Town() { ID = 405, TownName = "Gönen", CityID = 32 },
                new Town() { ID = 406, TownName = "Yenişarbademli", CityID = 32 },
                new Town() { ID = 407, TownName = "Anamur", CityID = 33 },
                new Town() { ID = 408, TownName = "Erdemli", CityID = 33 },
                new Town() { ID = 409, TownName = "Gülnar", CityID = 33 },
                new Town() { ID = 410, TownName = "Mut", CityID = 33 },
                new Town() { ID = 411, TownName = "Silifke", CityID = 33 },
                new Town() { ID = 412, TownName = "Tarsus", CityID = 33 },
                new Town() { ID = 413, TownName = "Aydıncık", CityID = 33 },
                new Town() { ID = 414, TownName = "Bozyazı", CityID = 33 },
                new Town() { ID = 415, TownName = "Çamlıyayla", CityID = 33 },
                new Town() { ID = 416, TownName = "Akdeniz", CityID = 33 },
                new Town() { ID = 417, TownName = "Mezitli", CityID = 33 },
                new Town() { ID = 418, TownName = "Toroslar", CityID = 33 },
                new Town() { ID = 419, TownName = "Yenişehir", CityID = 33 },
                new Town() { ID = 420, TownName = "Adalar", CityID = 34 },
                new Town() { ID = 421, TownName = "Bakırköy", CityID = 34 },
                new Town() { ID = 422, TownName = "Beşiktaş", CityID = 34 },
                new Town() { ID = 423, TownName = "Beykoz", CityID = 34 },
                new Town() { ID = 424, TownName = "Beyoğlu", CityID = 34 },
                new Town() { ID = 425, TownName = "Çatalca", CityID = 34 },
                new Town() { ID = 426, TownName = "Eyüp", CityID = 34 },
                new Town() { ID = 427, TownName = "Fatih", CityID = 34 },
                new Town() { ID = 428, TownName = "Gaziosmanpaşa", CityID = 34 },
                new Town() { ID = 429, TownName = "Kadıköy", CityID = 34 },
                new Town() { ID = 430, TownName = "Kartal", CityID = 34 },
                new Town() { ID = 431, TownName = "Sarıyer", CityID = 34 },
                new Town() { ID = 432, TownName = "Silivri", CityID = 34 },
                new Town() { ID = 433, TownName = "Şile", CityID = 34 },
                new Town() { ID = 434, TownName = "Şişli", CityID = 34 },
                new Town() { ID = 435, TownName = "Üsküdar", CityID = 34 },
                new Town() { ID = 436, TownName = "Zeytinburnu", CityID = 34 },
                new Town() { ID = 437, TownName = "Büyükçekmece", CityID = 34 },
                new Town() { ID = 438, TownName = "Kağıthane", CityID = 34 },
                new Town() { ID = 439, TownName = "Küçükçekmece", CityID = 34 },
                new Town() { ID = 440, TownName = "Pendik", CityID = 34 },
                new Town() { ID = 441, TownName = "Ümraniye", CityID = 34 },
                new Town() { ID = 442, TownName = "Bayrampaşa", CityID = 34 },
                new Town() { ID = 443, TownName = "Avcılar", CityID = 34 },
                new Town() { ID = 444, TownName = "Bağcılar", CityID = 34 },
                new Town() { ID = 445, TownName = "Bahçelievler", CityID = 34 },
                new Town() { ID = 446, TownName = "Güngören", CityID = 34 },
                new Town() { ID = 447, TownName = "Maltepe", CityID = 34 },
                new Town() { ID = 448, TownName = "Sultanbeyli", CityID = 34 },
                new Town() { ID = 449, TownName = "Tuzla", CityID = 34 },
                new Town() { ID = 450, TownName = "Esenler", CityID = 34 },
                new Town() { ID = 451, TownName = "Arnavutköy", CityID = 34 },
                new Town() { ID = 452, TownName = "Ataşehir", CityID = 34 },
                new Town() { ID = 453, TownName = "Başakşehir", CityID = 34 },
                new Town() { ID = 454, TownName = "Beylikdüzü", CityID = 34 },
                new Town() { ID = 455, TownName = "Çekmeköy", CityID = 34 },
                new Town() { ID = 456, TownName = "Esenyurt", CityID = 34 },
                new Town() { ID = 457, TownName = "Sancaktepe", CityID = 34 },
                new Town() { ID = 458, TownName = "Sultangazi", CityID = 34 },
                new Town() { ID = 459, TownName = "Aliağa", CityID = 35 },
                new Town() { ID = 460, TownName = "Bayındır", CityID = 35 },
                new Town() { ID = 461, TownName = "Bergama", CityID = 35 },
                new Town() { ID = 462, TownName = "Bornova", CityID = 35 },
                new Town() { ID = 463, TownName = "Çeşme", CityID = 35 },
                new Town() { ID = 464, TownName = "Dikili", CityID = 35 },
                new Town() { ID = 465, TownName = "Foça", CityID = 35 },
                new Town() { ID = 466, TownName = "Karaburun", CityID = 35 },
                new Town() { ID = 467, TownName = "Karşıyaka", CityID = 35 },
                new Town() { ID = 468, TownName = "Kemalpaşa", CityID = 35 },
                new Town() { ID = 469, TownName = "Kınık", CityID = 35 },
                new Town() { ID = 470, TownName = "Kiraz", CityID = 35 },
                new Town() { ID = 471, TownName = "Menemen", CityID = 35 },
                new Town() { ID = 472, TownName = "Ödemiş", CityID = 35 },
                new Town() { ID = 473, TownName = "Seferihisar", CityID = 35 },
                new Town() { ID = 474, TownName = "Selçuk", CityID = 35 },
                new Town() { ID = 475, TownName = "Tire", CityID = 35 },
                new Town() { ID = 476, TownName = "Torbalı", CityID = 35 },
                new Town() { ID = 477, TownName = "Urla", CityID = 35 },
                new Town() { ID = 478, TownName = "Beydağ", CityID = 35 },
                new Town() { ID = 479, TownName = "Buca", CityID = 35 },
                new Town() { ID = 480, TownName = "Konak", CityID = 35 },
                new Town() { ID = 481, TownName = "Menderes", CityID = 35 },
                new Town() { ID = 482, TownName = "Balçova", CityID = 35 },
                new Town() { ID = 483, TownName = "Çiğli", CityID = 35 },
                new Town() { ID = 484, TownName = "Gaziemir", CityID = 35 },
                new Town() { ID = 485, TownName = "Narlıdere", CityID = 35 },
                new Town() { ID = 486, TownName = "Güzelbahçe", CityID = 35 },
                new Town() { ID = 487, TownName = "Bayraklı", CityID = 35 },
                new Town() { ID = 488, TownName = "Karabağlar", CityID = 35 },
                new Town() { ID = 489, TownName = "Arpaçay", CityID = 36 },
                new Town() { ID = 490, TownName = "Digor", CityID = 36 },
                new Town() { ID = 491, TownName = "Kağızman", CityID = 36 },
                new Town() { ID = 492, TownName = "Merkez", CityID = 36 },
                new Town() { ID = 493, TownName = "Sarıkamış", CityID = 36 },
                new Town() { ID = 494, TownName = "Selim", CityID = 36 },
                new Town() { ID = 495, TownName = "Susuz", CityID = 36 },
                new Town() { ID = 496, TownName = "Akyaka", CityID = 36 },
                new Town() { ID = 497, TownName = "Abana", CityID = 37 },
                new Town() { ID = 498, TownName = "Araç", CityID = 37 },
                new Town() { ID = 499, TownName = "Azdavay", CityID = 37 },
                new Town() { ID = 500, TownName = "Bozkurt", CityID = 37 },
                new Town() { ID = 501, TownName = "Cide", CityID = 37 },
                new Town() { ID = 502, TownName = "Çatalzeytin", CityID = 37 },
                new Town() { ID = 503, TownName = "Daday", CityID = 37 },
                new Town() { ID = 504, TownName = "Devrekani", CityID = 37 },
                new Town() { ID = 505, TownName = "İnebolu", CityID = 37 },
                new Town() { ID = 506, TownName = "Merkez", CityID = 37 },
                new Town() { ID = 507, TownName = "Küre", CityID = 37 },
                new Town() { ID = 508, TownName = "Taşköprü", CityID = 37 },
                new Town() { ID = 509, TownName = "Tosya", CityID = 37 },
                new Town() { ID = 510, TownName = "İhsangazi", CityID = 37 },
                new Town() { ID = 511, TownName = "Pınarbaşı", CityID = 37 },
                new Town() { ID = 512, TownName = "Şenpazar", CityID = 37 },
                new Town() { ID = 513, TownName = "Ağlı", CityID = 37 },
                new Town() { ID = 514, TownName = "Doğanyurt", CityID = 37 },
                new Town() { ID = 515, TownName = "Hanönü", CityID = 37 },
                new Town() { ID = 516, TownName = "Seydiler", CityID = 37 },
                new Town() { ID = 517, TownName = "Bünyan", CityID = 38 },
                new Town() { ID = 518, TownName = "Develi", CityID = 38 },
                new Town() { ID = 519, TownName = "Felahiye", CityID = 38 },
                new Town() { ID = 520, TownName = "İncesu", CityID = 38 },
                new Town() { ID = 521, TownName = "Pınarbaşı", CityID = 38 },
                new Town() { ID = 522, TownName = "Sarıoğlan", CityID = 38 },
                new Town() { ID = 523, TownName = "Sarız", CityID = 38 },
                new Town() { ID = 524, TownName = "Tomarza", CityID = 38 },
                new Town() { ID = 525, TownName = "Yahyalı", CityID = 38 },
                new Town() { ID = 526, TownName = "Yeşilhisar", CityID = 38 },
                new Town() { ID = 527, TownName = "Akkışla", CityID = 38 },
                new Town() { ID = 528, TownName = "Talas", CityID = 38 },
                new Town() { ID = 529, TownName = "Kocasinan", CityID = 38 },
                new Town() { ID = 530, TownName = "Melikgazi", CityID = 38 },
                new Town() { ID = 531, TownName = "Hacılar", CityID = 38 },
                new Town() { ID = 532, TownName = "Özvatan", CityID = 38 },
                new Town() { ID = 533, TownName = "Babaeski", CityID = 39 },
                new Town() { ID = 534, TownName = "Demirköy", CityID = 39 },
                new Town() { ID = 535, TownName = "Merkez", CityID = 39 },
                new Town() { ID = 536, TownName = "Kofçaz", CityID = 39 },
                new Town() { ID = 537, TownName = "Lüleburgaz", CityID = 39 },
                new Town() { ID = 538, TownName = "Pehlivanköy", CityID = 39 },
                new Town() { ID = 539, TownName = "Pınarhisar", CityID = 39 },
                new Town() { ID = 540, TownName = "Vize", CityID = 39 },
                new Town() { ID = 541, TownName = "Çiçekdağı", CityID = 40 },
                new Town() { ID = 542, TownName = "Kaman", CityID = 40 },
                new Town() { ID = 543, TownName = "Merkez", CityID = 40 },
                new Town() { ID = 544, TownName = "Mucur", CityID = 40 },
                new Town() { ID = 545, TownName = "Akpınar", CityID = 40 },
                new Town() { ID = 546, TownName = "Akçakent", CityID = 40 },
                new Town() { ID = 547, TownName = "Boztepe", CityID = 40 },
                new Town() { ID = 548, TownName = "Gebze", CityID = 41 },
                new Town() { ID = 549, TownName = "Gölcük", CityID = 41 },
                new Town() { ID = 550, TownName = "Kandıra", CityID = 41 },
                new Town() { ID = 551, TownName = "Karamürsel", CityID = 41 },
                new Town() { ID = 552, TownName = "Körfez", CityID = 41 },
                new Town() { ID = 553, TownName = "Derince", CityID = 41 },
                new Town() { ID = 554, TownName = "Başiskele", CityID = 41 },
                new Town() { ID = 555, TownName = "Çayırova", CityID = 41 },
                new Town() { ID = 556, TownName = "Darıca", CityID = 41 },
                new Town() { ID = 557, TownName = "Dilovası", CityID = 41 },
                new Town() { ID = 558, TownName = "İzmit", CityID = 41 },
                new Town() { ID = 559, TownName = "Kartepe", CityID = 41 },
                new Town() { ID = 560, TownName = "Akşehir", CityID = 42 },
                new Town() { ID = 561, TownName = "Beyşehir", CityID = 42 },
                new Town() { ID = 562, TownName = "Bozkır", CityID = 42 },
                new Town() { ID = 563, TownName = "Cihanbeyli", CityID = 42 },
                new Town() { ID = 564, TownName = "Çumra", CityID = 42 },
                new Town() { ID = 565, TownName = "Doğanhisar", CityID = 42 },
                new Town() { ID = 566, TownName = "Konya", CityID = 42 },
                new Town() { ID = 567, TownName = "Hadim", CityID = 42 },
                new Town() { ID = 568, TownName = "Ilgın", CityID = 42 },
                new Town() { ID = 569, TownName = "Kadınhanı", CityID = 42 },
                new Town() { ID = 570, TownName = "Karapınar", CityID = 42 },
                new Town() { ID = 571, TownName = "Kulu", CityID = 42 },
                new Town() { ID = 572, TownName = "Sarayönü", CityID = 42 },
                new Town() { ID = 573, TownName = "Seydişehir", CityID = 42 },
                new Town() { ID = 574, TownName = "Yunak", CityID = 42 },
                new Town() { ID = 575, TownName = "Akören", CityID = 42 },
                new Town() { ID = 576, TownName = "Altınekin", CityID = 42 },
                new Town() { ID = 577, TownName = "Derebucak", CityID = 42 },
                new Town() { ID = 578, TownName = "Hüyük", CityID = 42 },
                new Town() { ID = 579, TownName = "Karatay", CityID = 42 },
                new Town() { ID = 580, TownName = "Meram", CityID = 42 },
                new Town() { ID = 581, TownName = "Selçuklu", CityID = 42 },
                new Town() { ID = 582, TownName = "Taşkent", CityID = 42 },
                new Town() { ID = 583, TownName = "Ahırlı", CityID = 42 },
                new Town() { ID = 584, TownName = "Çeltik", CityID = 42 },
                new Town() { ID = 585, TownName = "Derbent", CityID = 42 },
                new Town() { ID = 586, TownName = "Emirgazi", CityID = 42 },
                new Town() { ID = 587, TownName = "Güneysınır", CityID = 42 },
                new Town() { ID = 588, TownName = "Halkapınar", CityID = 42 },
                new Town() { ID = 589, TownName = "Tuzlukçu", CityID = 42 },
                new Town() { ID = 590, TownName = "Yalıhüyük", CityID = 42 },
                new Town() { ID = 591, TownName = "Altıntaş", CityID = 43 },
                new Town() { ID = 592, TownName = "Domaniç", CityID = 43 },
                new Town() { ID = 593, TownName = "Emet", CityID = 43 },
                new Town() { ID = 594, TownName = "Gediz", CityID = 43 },
                new Town() { ID = 595, TownName = "Merkez", CityID = 43 },
                new Town() { ID = 596, TownName = "Simav", CityID = 43 },
                new Town() { ID = 597, TownName = "Tavşanlı", CityID = 43 },
                new Town() { ID = 598, TownName = "Aslanapa", CityID = 43 },
                new Town() { ID = 599, TownName = "Dumlupınar", CityID = 43 },
                new Town() { ID = 600, TownName = "Hisarcık", CityID = 43 },
                new Town() { ID = 601, TownName = "Şaphane", CityID = 43 },
                new Town() { ID = 602, TownName = "Çavdarhisar", CityID = 43 },
                new Town() { ID = 603, TownName = "Pazarlar", CityID = 43 },
                new Town() { ID = 604, TownName = "Akçadağ", CityID = 44 },
                new Town() { ID = 605, TownName = "Arapgir", CityID = 44 },
                new Town() { ID = 606, TownName = "Arguvan", CityID = 44 },
                new Town() { ID = 607, TownName = "Darende", CityID = 44 },
                new Town() { ID = 608, TownName = "Doğanşehir", CityID = 44 },
                new Town() { ID = 609, TownName = "Hekimhan", CityID = 44 },
                new Town() { ID = 610, TownName = "Pütürge", CityID = 44 },
                new Town() { ID = 611, TownName = "Yeşilyurt", CityID = 44 },
                new Town() { ID = 612, TownName = "Battalgazi", CityID = 44 },
                new Town() { ID = 613, TownName = "Doğanyol", CityID = 44 },
                new Town() { ID = 614, TownName = "Kale", CityID = 44 },
                new Town() { ID = 615, TownName = "Kuluncak", CityID = 44 },
                new Town() { ID = 616, TownName = "Yazıhan", CityID = 44 },
                new Town() { ID = 617, TownName = "Akhisar", CityID = 45 },
                new Town() { ID = 618, TownName = "Alaşehir", CityID = 45 },
                new Town() { ID = 619, TownName = "Demirci", CityID = 45 },
                new Town() { ID = 620, TownName = "Gördes", CityID = 45 },
                new Town() { ID = 621, TownName = "Kırkağaç", CityID = 45 },
                new Town() { ID = 622, TownName = "Kula", CityID = 45 },
                new Town() { ID = 623, TownName = "Salihli", CityID = 45 },
                new Town() { ID = 624, TownName = "Sarıgöl", CityID = 45 },
                new Town() { ID = 625, TownName = "Saruhanlı", CityID = 45 },
                new Town() { ID = 626, TownName = "Selendi", CityID = 45 },
                new Town() { ID = 627, TownName = "Soma", CityID = 45 },
                new Town() { ID = 628, TownName = "Turgutlu", CityID = 45 },
                new Town() { ID = 629, TownName = "Ahmetli", CityID = 45 },
                new Town() { ID = 630, TownName = "Gölmarmara", CityID = 45 },
                new Town() { ID = 631, TownName = "Köprübaşı", CityID = 45 },
                new Town() { ID = 632, TownName = "Şehzadeler", CityID = 45 },
                new Town() { ID = 633, TownName = "Yunusemre", CityID = 45 },
                new Town() { ID = 634, TownName = "Afşin", CityID = 46 },
                new Town() { ID = 635, TownName = "Andırın", CityID = 46 },
                new Town() { ID = 636, TownName = "Elbistan", CityID = 46 },
                new Town() { ID = 637, TownName = "Göksun", CityID = 46 },
                new Town() { ID = 638, TownName = "Pazarcık", CityID = 46 },
                new Town() { ID = 639, TownName = "Türkoğlu", CityID = 46 },
                new Town() { ID = 640, TownName = "Çağlayancerit", CityID = 46 },
                new Town() { ID = 641, TownName = "Ekinözü", CityID = 46 },
                new Town() { ID = 642, TownName = "Nurhak", CityID = 46 },
                new Town() { ID = 643, TownName = "Dulkadiroğlu", CityID = 46 },
                new Town() { ID = 644, TownName = "Onikişubat", CityID = 46 },
                new Town() { ID = 645, TownName = "Derik", CityID = 47 },
                new Town() { ID = 646, TownName = "Kızıltepe", CityID = 47 },
                new Town() { ID = 647, TownName = "Mazıdağı", CityID = 47 },
                new Town() { ID = 648, TownName = "Midyat", CityID = 47 },
                new Town() { ID = 649, TownName = "Nusaybin", CityID = 47 },
                new Town() { ID = 650, TownName = "Ömerli", CityID = 47 },
                new Town() { ID = 651, TownName = "Savur", CityID = 47 },
                new Town() { ID = 652, TownName = "Dargeçit", CityID = 47 },
                new Town() { ID = 653, TownName = "Yeşilli", CityID = 47 },
                new Town() { ID = 654, TownName = "Artuklu", CityID = 47 },
                new Town() { ID = 655, TownName = "Bodrum", CityID = 48 },
                new Town() { ID = 656, TownName = "Datça", CityID = 48 },
                new Town() { ID = 657, TownName = "Fethiye", CityID = 48 },
                new Town() { ID = 658, TownName = "Köyceğiz", CityID = 48 },
                new Town() { ID = 659, TownName = "Marmaris", CityID = 48 },
                new Town() { ID = 660, TownName = "Milas", CityID = 48 },
                new Town() { ID = 661, TownName = "Ula", CityID = 48 },
                new Town() { ID = 662, TownName = "Yatağan", CityID = 48 },
                new Town() { ID = 663, TownName = "Dalaman", CityID = 48 },
                new Town() { ID = 664, TownName = "Ortaca", CityID = 48 },
                new Town() { ID = 665, TownName = "Kavaklıdere", CityID = 48 },
                new Town() { ID = 666, TownName = "Menteşe", CityID = 48 },
                new Town() { ID = 667, TownName = "Seydikemer", CityID = 48 },
                new Town() { ID = 668, TownName = "Bulanık", CityID = 49 },
                new Town() { ID = 669, TownName = "Malazgirt", CityID = 49 },
                new Town() { ID = 670, TownName = "Muş Merkez", CityID = 49 },
                new Town() { ID = 671, TownName = "Varto", CityID = 49 },
                new Town() { ID = 672, TownName = "Hasköy", CityID = 49 },
                new Town() { ID = 673, TownName = "Korkut", CityID = 49 },
                new Town() { ID = 674, TownName = "Avanos", CityID = 50 },
                new Town() { ID = 675, TownName = "Derinkuyu", CityID = 50 },
                new Town() { ID = 676, TownName = "Gülşehir", CityID = 50 },
                new Town() { ID = 677, TownName = "Hacıbektaş", CityID = 50 },
                new Town() { ID = 678, TownName = "Kozaklı", CityID = 50 },
                new Town() { ID = 679, TownName = "Merkez", CityID = 50 },
                new Town() { ID = 680, TownName = "Ürgüp", CityID = 50 },
                new Town() { ID = 681, TownName = "Acıgöl", CityID = 50 },
                new Town() { ID = 682, TownName = "Bor", CityID = 51 },
                new Town() { ID = 683, TownName = "Çamardı", CityID = 51 },
                new Town() { ID = 684, TownName = "Merkez", CityID = 51 },
                new Town() { ID = 685, TownName = "Ulukışla", CityID = 51 },
                new Town() { ID = 686, TownName = "Altunhisar", CityID = 51 },
                new Town() { ID = 687, TownName = "Çiftlik", CityID = 51 },
                new Town() { ID = 688, TownName = "Akkuş", CityID = 52 },
                new Town() { ID = 689, TownName = "Aybastı", CityID = 52 },
                new Town() { ID = 690, TownName = "Fatsa", CityID = 52 },
                new Town() { ID = 691, TownName = "Gölköy", CityID = 52 },
                new Town() { ID = 692, TownName = "Korgan", CityID = 52 },
                new Town() { ID = 693, TownName = "Kumru", CityID = 52 },
                new Town() { ID = 694, TownName = "Mesudiye", CityID = 52 },
                new Town() { ID = 695, TownName = "Perşembe", CityID = 52 },
                new Town() { ID = 696, TownName = "Ulubey", CityID = 52 },
                new Town() { ID = 697, TownName = "Ünye", CityID = 52 },
                new Town() { ID = 698, TownName = "Gülyalı", CityID = 52 },
                new Town() { ID = 699, TownName = "Gürgentepe", CityID = 52 },
                new Town() { ID = 700, TownName = "Çamaş", CityID = 52 },
                new Town() { ID = 701, TownName = "Çatalpınar", CityID = 52 },
                new Town() { ID = 702, TownName = "Çaybaşı", CityID = 52 },
                new Town() { ID = 703, TownName = "İkizce", CityID = 52 },
                new Town() { ID = 704, TownName = "Kabadüz", CityID = 52 },
                new Town() { ID = 705, TownName = "Kabataş", CityID = 52 },
                new Town() { ID = 706, TownName = "Altınordu", CityID = 52 },
                new Town() { ID = 707, TownName = "Ardeşen", CityID = 53 },
                new Town() { ID = 708, TownName = "Çamlıhemşin", CityID = 53 },
                new Town() { ID = 709, TownName = "Çayeli", CityID = 53 },
                new Town() { ID = 710, TownName = "Fındıklı", CityID = 53 },
                new Town() { ID = 711, TownName = "İkizdere", CityID = 53 },
                new Town() { ID = 712, TownName = "Kalkandere", CityID = 53 },
                new Town() { ID = 713, TownName = "Pazar", CityID = 53 },
                new Town() { ID = 714, TownName = "Rize Merkez", CityID = 53 },
                new Town() { ID = 715, TownName = "Güneysu", CityID = 53 },
                new Town() { ID = 716, TownName = "Derepazarı", CityID = 53 },
                new Town() { ID = 717, TownName = "Hemşin", CityID = 53 },
                new Town() { ID = 718, TownName = "İyidere", CityID = 53 },
                new Town() { ID = 719, TownName = "Akyazı", CityID = 54 },
                new Town() { ID = 720, TownName = "Geyve", CityID = 54 },
                new Town() { ID = 721, TownName = "Hendek", CityID = 54 },
                new Town() { ID = 722, TownName = "Karasu", CityID = 54 },
                new Town() { ID = 723, TownName = "Kaynarca", CityID = 54 },
                new Town() { ID = 724, TownName = "Sapanca", CityID = 54 },
                new Town() { ID = 725, TownName = "Kocaali", CityID = 54 },
                new Town() { ID = 726, TownName = "Pamukova", CityID = 54 },
                new Town() { ID = 727, TownName = "Taraklı", CityID = 54 },
                new Town() { ID = 728, TownName = "Ferizli", CityID = 54 },
                new Town() { ID = 729, TownName = "Karapürçek", CityID = 54 },
                new Town() { ID = 730, TownName = "Söğütlü", CityID = 54 },
                new Town() { ID = 731, TownName = "Adapazarı", CityID = 54 },
                new Town() { ID = 732, TownName = "Arifiye", CityID = 54 },
                new Town() { ID = 733, TownName = "Erenler", CityID = 54 },
                new Town() { ID = 734, TownName = "Serdivan", CityID = 54 },
                new Town() { ID = 735, TownName = "Alaçam", CityID = 55 },
                new Town() { ID = 736, TownName = "Bafra", CityID = 55 },
                new Town() { ID = 737, TownName = "Çarşamba", CityID = 55 },
                new Town() { ID = 738, TownName = "Havza", CityID = 55 },
                new Town() { ID = 739, TownName = "Kavak", CityID = 55 },
                new Town() { ID = 740, TownName = "Ladik", CityID = 55 },
                new Town() { ID = 741, TownName = "Terme", CityID = 55 },
                new Town() { ID = 742, TownName = "Vezirköprü", CityID = 55 },
                new Town() { ID = 743, TownName = "Asarcık", CityID = 55 },
                new Town() { ID = 744, TownName = "43604", CityID = 55 },
                new Town() { ID = 745, TownName = "Salıpazarı", CityID = 55 },
                new Town() { ID = 746, TownName = "Tekkeköy", CityID = 55 },
                new Town() { ID = 747, TownName = "Ayvacık", CityID = 55 },
                new Town() { ID = 748, TownName = "Yakakent", CityID = 55 },
                new Town() { ID = 749, TownName = "Atakum", CityID = 55 },
                new Town() { ID = 750, TownName = "Canik", CityID = 55 },
                new Town() { ID = 751, TownName = "İlkadım", CityID = 55 },
                new Town() { ID = 752, TownName = "Baykan", CityID = 56 },
                new Town() { ID = 753, TownName = "Eruh", CityID = 56 },
                new Town() { ID = 754, TownName = "Kurtalan", CityID = 56 },
                new Town() { ID = 755, TownName = "Pervari", CityID = 56 },
                new Town() { ID = 756, TownName = "Merkez", CityID = 56 },
                new Town() { ID = 757, TownName = "Şirvan", CityID = 56 },
                new Town() { ID = 758, TownName = "Tillo", CityID = 56 },
                new Town() { ID = 759, TownName = "Ayancık", CityID = 57 },
                new Town() { ID = 760, TownName = "Boyabat", CityID = 57 },
                new Town() { ID = 761, TownName = "Durağan", CityID = 57 },
                new Town() { ID = 762, TownName = "Erfelek", CityID = 57 },
                new Town() { ID = 763, TownName = "Gerze", CityID = 57 },
                new Town() { ID = 764, TownName = "Merkez", CityID = 57 },
                new Town() { ID = 765, TownName = "Türkeli", CityID = 57 },
                new Town() { ID = 766, TownName = "Dikmen", CityID = 57 },
                new Town() { ID = 767, TownName = "Saraydüzü", CityID = 57 },
                new Town() { ID = 768, TownName = "Divriği", CityID = 58 },
                new Town() { ID = 769, TownName = "Gemerek", CityID = 58 },
                new Town() { ID = 770, TownName = "Gürün", CityID = 58 },
                new Town() { ID = 771, TownName = "Hafik", CityID = 58 },
                new Town() { ID = 772, TownName = "İmranlı", CityID = 58 },
                new Town() { ID = 773, TownName = "Kangal", CityID = 58 },
                new Town() { ID = 774, TownName = "Koyulhisar", CityID = 58 },
                new Town() { ID = 775, TownName = "Merkez", CityID = 58 },
                new Town() { ID = 776, TownName = "Suşehri", CityID = 58 },
                new Town() { ID = 777, TownName = "Şarkışla", CityID = 58 },
                new Town() { ID = 778, TownName = "Yıldızeli", CityID = 58 },
                new Town() { ID = 779, TownName = "Zara", CityID = 58 },
                new Town() { ID = 780, TownName = "Akıncılar", CityID = 58 },
                new Town() { ID = 781, TownName = "Altınyayla", CityID = 58 },
                new Town() { ID = 782, TownName = "Doğanşar", CityID = 58 },
                new Town() { ID = 783, TownName = "Gölova", CityID = 58 },
                new Town() { ID = 784, TownName = "Ulaş", CityID = 58 },
                new Town() { ID = 785, TownName = "Çerkezköy", CityID = 59 },
                new Town() { ID = 786, TownName = "Çorlu", CityID = 59 },
                new Town() { ID = 787, TownName = "Hayrabolu", CityID = 59 },
                new Town() { ID = 788, TownName = "Malkara", CityID = 59 },
                new Town() { ID = 789, TownName = "Muratlı", CityID = 59 },
                new Town() { ID = 790, TownName = "Saray", CityID = 59 },
                new Town() { ID = 791, TownName = "Şarköy", CityID = 59 },
                new Town() { ID = 792, TownName = "Marmaraereğlisi", CityID = 59 },
                new Town() { ID = 793, TownName = "Ergene", CityID = 59 },
                new Town() { ID = 794, TownName = "Kapaklı", CityID = 59 },
                new Town() { ID = 795, TownName = "Süleymanpaşa", CityID = 59 },
                new Town() { ID = 796, TownName = "Almus", CityID = 60 },
                new Town() { ID = 797, TownName = "Artova", CityID = 60 },
                new Town() { ID = 798, TownName = "Erbaa", CityID = 60 },
                new Town() { ID = 799, TownName = "Niksar", CityID = 60 },
                new Town() { ID = 800, TownName = "Reşadiye", CityID = 60 },
                new Town() { ID = 801, TownName = "Tokat Merkez", CityID = 60 },
                new Town() { ID = 802, TownName = "Turhal", CityID = 60 },
                new Town() { ID = 803, TownName = "Zile", CityID = 60 },
                new Town() { ID = 804, TownName = "Pazar", CityID = 60 },
                new Town() { ID = 805, TownName = "Yeşilyurt", CityID = 60 },
                new Town() { ID = 806, TownName = "Başçiftlik", CityID = 60 },
                new Town() { ID = 807, TownName = "Sulusaray", CityID = 60 },
                new Town() { ID = 808, TownName = "Akçaabat", CityID = 61 },
                new Town() { ID = 809, TownName = "Araklı", CityID = 61 },
                new Town() { ID = 810, TownName = "Arsin", CityID = 61 },
                new Town() { ID = 811, TownName = "Çaykara", CityID = 61 },
                new Town() { ID = 812, TownName = "Maçka", CityID = 61 },
                new Town() { ID = 813, TownName = "Of", CityID = 61 },
                new Town() { ID = 814, TownName = "Sürmene", CityID = 61 },
                new Town() { ID = 815, TownName = "Tonya", CityID = 61 },
                new Town() { ID = 816, TownName = "Vakfıkebir", CityID = 61 },
                new Town() { ID = 817, TownName = "Yomra", CityID = 61 },
                new Town() { ID = 818, TownName = "Beşikdüzü", CityID = 61 },
                new Town() { ID = 819, TownName = "Şalpazarı", CityID = 61 },
                new Town() { ID = 820, TownName = "Çarşıbaşı", CityID = 61 },
                new Town() { ID = 821, TownName = "Dernekpazarı", CityID = 61 },
                new Town() { ID = 822, TownName = "Düzköy", CityID = 61 },
                new Town() { ID = 823, TownName = "Hayrat", CityID = 61 },
                new Town() { ID = 824, TownName = "Köprübaşı", CityID = 61 },
                new Town() { ID = 825, TownName = "Ortahisar", CityID = 61 },
                new Town() { ID = 826, TownName = "Çemişgezek", CityID = 62 },
                new Town() { ID = 827, TownName = "Hozat", CityID = 62 },
                new Town() { ID = 828, TownName = "Mazgirt", CityID = 62 },
                new Town() { ID = 829, TownName = "Nazımiye", CityID = 62 },
                new Town() { ID = 830, TownName = "Ovacık", CityID = 62 },
                new Town() { ID = 831, TownName = "Pertek", CityID = 62 },
                new Town() { ID = 832, TownName = "Pülümür", CityID = 62 },
                new Town() { ID = 833, TownName = "Merkez", CityID = 62 },
                new Town() { ID = 834, TownName = "Akçakale", CityID = 63 },
                new Town() { ID = 835, TownName = "Birecik", CityID = 63 },
                new Town() { ID = 836, TownName = "Bozova", CityID = 63 },
                new Town() { ID = 837, TownName = "Ceylanpınar", CityID = 63 },
                new Town() { ID = 838, TownName = "Halfeti", CityID = 63 },
                new Town() { ID = 839, TownName = "Hilvan", CityID = 63 },
                new Town() { ID = 840, TownName = "Siverek", CityID = 63 },
                new Town() { ID = 841, TownName = "Suruç", CityID = 63 },
                new Town() { ID = 842, TownName = "Viranşehir", CityID = 63 },
                new Town() { ID = 843, TownName = "Harran", CityID = 63 },
                new Town() { ID = 844, TownName = "Eyyübiye", CityID = 63 },
                new Town() { ID = 845, TownName = "Haliliye", CityID = 63 },
                new Town() { ID = 846, TownName = "Karaköprü", CityID = 63 },
                new Town() { ID = 847, TownName = "Banaz", CityID = 64 },
                new Town() { ID = 848, TownName = "Eşme", CityID = 64 },
                new Town() { ID = 849, TownName = "Karahallı", CityID = 64 },
                new Town() { ID = 850, TownName = "Sivaslı", CityID = 64 },
                new Town() { ID = 851, TownName = "Ulubey", CityID = 64 },
                new Town() { ID = 852, TownName = "Uşak Merkez", CityID = 64 },
                new Town() { ID = 853, TownName = "Başkale", CityID = 65 },
                new Town() { ID = 854, TownName = "Çatak", CityID = 65 },
                new Town() { ID = 855, TownName = "Erciş", CityID = 65 },
                new Town() { ID = 856, TownName = "Gevaş", CityID = 65 },
                new Town() { ID = 857, TownName = "Gürpınar", CityID = 65 },
                new Town() { ID = 858, TownName = "Muradiye", CityID = 65 },
                new Town() { ID = 859, TownName = "Özalp", CityID = 65 },
                new Town() { ID = 860, TownName = "Bahçesaray", CityID = 65 },
                new Town() { ID = 861, TownName = "Çaldıran", CityID = 65 },
                new Town() { ID = 862, TownName = "Edremit", CityID = 65 },
                new Town() { ID = 863, TownName = "Saray", CityID = 65 },
                new Town() { ID = 864, TownName = "İpekyolu", CityID = 65 },
                new Town() { ID = 865, TownName = "Tuşba", CityID = 65 },
                new Town() { ID = 866, TownName = "Akdağmadeni", CityID = 66 },
                new Town() { ID = 867, TownName = "Boğazlıyan", CityID = 66 },
                new Town() { ID = 868, TownName = "Çayıralan", CityID = 66 },
                new Town() { ID = 869, TownName = "Çekerek", CityID = 66 },
                new Town() { ID = 870, TownName = "Sarıkaya", CityID = 66 },
                new Town() { ID = 871, TownName = "Sorgun", CityID = 66 },
                new Town() { ID = 872, TownName = "Şefaatli", CityID = 66 },
                new Town() { ID = 873, TownName = "Yerköy", CityID = 66 },
                new Town() { ID = 874, TownName = "Yozgat Merkez", CityID = 66 },
                new Town() { ID = 875, TownName = "Aydıncık", CityID = 66 },
                new Town() { ID = 876, TownName = "Çandır", CityID = 66 },
                new Town() { ID = 877, TownName = "Kadışehri", CityID = 66 },
                new Town() { ID = 878, TownName = "Saraykent", CityID = 66 },
                new Town() { ID = 879, TownName = "Yenifakılı", CityID = 66 },
                new Town() { ID = 880, TownName = "Çaycuma", CityID = 67 },
                new Town() { ID = 881, TownName = "Devrek", CityID = 67 },
                new Town() { ID = 882, TownName = "Ereğli", CityID = 67 },
                new Town() { ID = 883, TownName = "Merkez", CityID = 67 },
                new Town() { ID = 884, TownName = "Alaplı", CityID = 67 },
                new Town() { ID = 885, TownName = "Gökçebey", CityID = 67 },
                new Town() { ID = 886, TownName = "Kilimli", CityID = 67 },
                new Town() { ID = 887, TownName = "Kozlu", CityID = 67 },
                new Town() { ID = 888, TownName = "Merkez", CityID = 68 },
                new Town() { ID = 889, TownName = "Ortaköy", CityID = 68 },
                new Town() { ID = 890, TownName = "Ağaçören", CityID = 68 },
                new Town() { ID = 891, TownName = "Güzelyurt", CityID = 68 },
                new Town() { ID = 892, TownName = "Sarıyahşi", CityID = 68 },
                new Town() { ID = 893, TownName = "Eskil", CityID = 68 },
                new Town() { ID = 894, TownName = "Gülağaç", CityID = 68 },
                new Town() { ID = 895, TownName = "Merkez", CityID = 69 },
                new Town() { ID = 896, TownName = "Aydıntepe", CityID = 69 },
                new Town() { ID = 897, TownName = "Demirözü", CityID = 69 },
                new Town() { ID = 898, TownName = "Ermenek", CityID = 70 },
                new Town() { ID = 899, TownName = "Merkez", CityID = 70 },
                new Town() { ID = 900, TownName = "Ayrancı", CityID = 70 },
                new Town() { ID = 901, TownName = "Kazımkarabekir", CityID = 70 },
                new Town() { ID = 902, TownName = "Başyayla", CityID = 70 },
                new Town() { ID = 903, TownName = "Sarıveliler", CityID = 70 },
                new Town() { ID = 904, TownName = "Delice", CityID = 71 },
                new Town() { ID = 905, TownName = "Keskin", CityID = 71 },
                new Town() { ID = 906, TownName = "Merkez", CityID = 71 },
                new Town() { ID = 907, TownName = "Sulakyurt", CityID = 71 },
                new Town() { ID = 908, TownName = "Bahşili", CityID = 71 },
                new Town() { ID = 909, TownName = "Balışeyh", CityID = 71 },
                new Town() { ID = 910, TownName = "Çelebi", CityID = 71 },
                new Town() { ID = 911, TownName = "Karakeçili", CityID = 71 },
                new Town() { ID = 912, TownName = "Yahşihan", CityID = 71 },
                new Town() { ID = 913, TownName = "Merkez", CityID = 72 },
                new Town() { ID = 914, TownName = "Beşiri", CityID = 72 },
                new Town() { ID = 915, TownName = "Gercüş", CityID = 72 },
                new Town() { ID = 916, TownName = "Kozluk", CityID = 72 },
                new Town() { ID = 917, TownName = "Sason", CityID = 72 },
                new Town() { ID = 918, TownName = "Hasankeyf", CityID = 72 },
                new Town() { ID = 919, TownName = "Beytüşşebap", CityID = 73 },
                new Town() { ID = 920, TownName = "Cizre", CityID = 73 },
                new Town() { ID = 921, TownName = "İdil", CityID = 73 },
                new Town() { ID = 922, TownName = "Silopi", CityID = 73 },
                new Town() { ID = 923, TownName = "Merkez", CityID = 73 },
                new Town() { ID = 924, TownName = "Uludere", CityID = 73 },
                new Town() { ID = 925, TownName = "Güçlükonak", CityID = 73 },
                new Town() { ID = 926, TownName = "Merkez", CityID = 74 },
                new Town() { ID = 927, TownName = "Kurucaşile", CityID = 74 },
                new Town() { ID = 928, TownName = "Ulus", CityID = 74 },
                new Town() { ID = 929, TownName = "Amasra", CityID = 74 },
                new Town() { ID = 930, TownName = "Merkez", CityID = 75 },
                new Town() { ID = 931, TownName = "Çıldır", CityID = 75 },
                new Town() { ID = 932, TownName = "Göle", CityID = 75 },
                new Town() { ID = 933, TownName = "Hanak", CityID = 75 },
                new Town() { ID = 934, TownName = "Posof", CityID = 75 },
                new Town() { ID = 935, TownName = "Damal", CityID = 75 },
                new Town() { ID = 936, TownName = "Aralık", CityID = 76 },
                new Town() { ID = 937, TownName = "Merkez", CityID = 76 },
                new Town() { ID = 938, TownName = "Tuzluca", CityID = 76 },
                new Town() { ID = 939, TownName = "Karakoyunlu", CityID = 76 },
                new Town() { ID = 940, TownName = "Merkez", CityID = 77 },
                new Town() { ID = 941, TownName = "Altınova", CityID = 77 },
                new Town() { ID = 942, TownName = "Armutlu", CityID = 77 },
                new Town() { ID = 943, TownName = "Çınarcık", CityID = 77 },
                new Town() { ID = 944, TownName = "Çiftlikköy", CityID = 77 },
                new Town() { ID = 945, TownName = "Termal", CityID = 77 },
                new Town() { ID = 946, TownName = "Eflani", CityID = 78 },
                new Town() { ID = 947, TownName = "Eskipazar", CityID = 78 },
                new Town() { ID = 948, TownName = "Merkez", CityID = 78 },
                new Town() { ID = 949, TownName = "Ovacık", CityID = 78 },
                new Town() { ID = 950, TownName = "Safranbolu", CityID = 78 },
                new Town() { ID = 951, TownName = "Yenice", CityID = 78 },
                new Town() { ID = 952, TownName = "Merkez", CityID = 79 },
                new Town() { ID = 953, TownName = "Elbeyli", CityID = 79 },
                new Town() { ID = 954, TownName = "Musabeyli", CityID = 79 },
                new Town() { ID = 955, TownName = "Polateli", CityID = 79 },
                new Town() { ID = 956, TownName = "Bahçe", CityID = 80 },
                new Town() { ID = 957, TownName = "Kadirli", CityID = 80 },
                new Town() { ID = 958, TownName = "Merkez", CityID = 80 },
                new Town() { ID = 959, TownName = "Düziçi", CityID = 80 },
                new Town() { ID = 960, TownName = "Hasanbeyli", CityID = 80 },
                new Town() { ID = 961, TownName = "Sumbas", CityID = 80 },
                new Town() { ID = 962, TownName = "Toprakkale", CityID = 80 },
                new Town() { ID = 963, TownName = "Akçakoca", CityID = 81 },
                new Town() { ID = 964, TownName = "Merkez", CityID = 81 },
                new Town() { ID = 965, TownName = "Yığılca", CityID = 81 },
                new Town() { ID = 966, TownName = "Cumayeri", CityID = 81 },
                new Town() { ID = 967, TownName = "Gölyaka", CityID = 81 },
                new Town() { ID = 968, TownName = "Çilimli", CityID = 81 },
                new Town() { ID = 969, TownName = "Gümüşova", CityID = 81 },
                new Town() { ID = 970, TownName = "Kaynaşlı", CityID = 81 }


                );
        }
    }
}
